### ISSUE TITLE
Tries to write new image to / (Permission denied)

### ISSUE THREAD

**Issue by danbruegge** [JuanPotato/Legofy#22] opened 2015-10-29 08:01 UTC
Hi,

legofy tries to write the new image to /. Results in a permission denied error.

```
$ python legofy/cli.py 2014-08-08.jpg
Static image detected, will now legofy and save as /lego_2014-08-08.png
Traceback (most recent call last):
  File "legofy/cli.py", line 17, in <module>
    main()
  File "/home/dan/workspace/playground/legofy/lib/python3.5/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/dan/workspace/playground/legofy/lib/python3.5/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/dan/workspace/playground/legofy/lib/python3.5/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dan/workspace/playground/legofy/lib/python3.5/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "legofy/cli.py", line 14, in main
    legofy.main(image, brick=brick)
  File "/home/dan/workspace/playground/legofy/lib/python3.5/site-packages/legofy-0.0.1-py3.5.egg/legofy/__init__.py", line 131, in main
    makeLegoImage(baseImage, brick).save(newFilename)
  File "/home/dan/workspace/playground/legofy/lib/python3.5/site-packages/PIL/Image.py", line 1659, in save
    fp = builtins.open(filename, "wb")
PermissionError: [Errno 13] Permission denied: '/lego_2014-08-08.png'
```

**Comment by grisu48** [comment] 2015-10-29 09:22
I have the same issue

**Comment by xsteadfastx** [comment] 2015-10-29 09:51
same here

**Comment by methou** [comment] 2015-10-29 09:53
I tried to use ./pic_name.png as a workaround, then it works.

**Comment by danbruegge** [comment] 2015-10-29 09:56
@methou nice, it worked. :)

**Comment by grisu48** [comment] 2015-10-29 09:59
@methou Worked for me too +1

**Comment by grisu48** [comment] 2015-10-29 11:47
Awesome - Just wanted to also push the following patch:
--- a/legofy/__init__.py
+++ b/legofy/__init__.py
@@ -81,7 +81,9 @@ def main(filename, brick, width=30, height=30, scale=1):
     baseImage = Image.open(filename)
     newSize = baseImage.size
     static = filename.lower().endswith(".gif") and is_animated(baseImage)
-    newFilename = '{0}/lego_{1}'.format(*os.path.split(filename))
+    (_path, _filename) = os.path.split(filename)
+    if len(_path) <= 0 : _path = "."
+    newFilename = '{0}/lego_{1}'.format(_path, _filename)
 
     if newSize[0] > 30 or newSize[1] > 30:
         if newSize[0] < newSize[1]:

**Comment by nabijaczleweli** [comment] 2015-10-29 17:52
@grisu48: either wrap that with \`\`\` or submit a PR

**Comment by drvinceknight** [comment] 2015-10-29 20:34
I'm having the same issue: how does when specify the output of the file? Is there any documentation anywhere?

**Comment by eyalzek** [comment] 2015-10-29 20:53
The output parameter is not used, what it does is take the original file name and create a file with the same name with 'lego_' prepended to it... The problem is when you specify a file path in the same working directory you are at (ie: test.jpg) the way it calculates the path at the moment will try to put the new file at '/lego_test.jpg' which will cause the permission denied error...

As suggested above, a temporary fix would be to pass the name of the file like so: ./test.jpg instead of: test.jpg

**Comment by drvinceknight** [comment] 2015-10-29 21:11
Ah great. I understand. Would you welcome a PR for this?

**Comment by JuanPotato** [comment] 2015-10-29 23:55
Sorry I haven't merged this yet, I've been working on the project and fixing bits before it got a lot of attention on /r/python or where ever most of you came from. I'm almost done and will look through the merges after I'm done.

**Comment by furas** [comment] 2015-10-30 15:27
You could use

    _path, _name = os.path.split(filename)
    newFilename = os.path.join(_path, 'lego_' + _name)

in place of

    newFilename = '{0}/lego_{1}'.format(*os.path.split(filename))

**Comment by JuanPotato** [comment] 2015-10-30 22:41
This should be fixed, please try with the newest code.

**Closed** 2015-10-30 22:52 UTC
